import './globals.css';
import Link from 'next/link';
import React from 'react';
export const metadata = {
  title: 'Cars application',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-sky-100 p-4">
        <header>
          <div className="mx-auto max-w-7xl px-4">
            <div className="mx-auto max-w-3xl">
              <h2 className="flex justify-evenly py-5 text-3xl font-bold tracking-tight text-gray-900">
                <Link href={'/'}>Home</Link>
                <Link href={'/car/new'}>Create new car</Link>
              </h2>
              {children}
            </div>
          </div>
        </header>
      </body>
    </html>
  );
}
